In [109]:
import json
import pandas as pd

In [110]:
df = pd.read_csv('games.csv')

In [111]:
df

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,3308904636,1503076540231,1944,9,2,1,2,2,0,2,...,10,2,0,4,0,55,-1,90,238,157
51486,3215685759,1496957179355,3304,9,2,1,1,2,2,2,...,11,7,4,4,1,157,55,119,154,105
51487,3322765040,1504029863961,2156,9,2,2,2,2,0,1,...,10,2,0,2,0,113,122,53,11,157
51488,3256675373,1499562036246,1475,9,2,2,2,2,0,2,...,11,3,0,1,0,154,39,51,90,114
51489,3317333020,1503612754059,1445,9,1,1,1,1,1,2,...,1,0,0,1,0,11,157,141,31,18

In [112]:
df.columns

Index(['gameId', 'creationTime', 'gameDuration', 'seasonId', 'winner',
       'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron',
       'firstDragon', 'firstRiftHerald', 't1_champ1id', 't1_champ1_sum1',
       't1_champ1_sum2', 't1_champ2id', 't1_champ2_sum1', 't1_champ2_sum2',
       't1_champ3id', 't1_champ3_sum1', 't1_champ3_sum2', 't1_champ4id',
       't1_champ4_sum1', 't1_champ4_sum2', 't1_champ5id', 't1_champ5_sum1',
       't1_champ5_sum2', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills',
       't1_dragonKills', 't1_riftHeraldKills', 't1_ban1', 't1_ban2', 't1_ban3',
       't1_ban4', 't1_ban5', 't2_champ1id', 't2_champ1_sum1', 't2_champ1_sum2',
       't2_champ2id', 't2_champ2_sum1', 't2_champ2_sum2', 't2_champ3id',
       't2_champ3_sum1', 't2_champ3_sum2', 't2_champ4id', 't2_champ4_sum1',
       't2_champ4_sum2', 't2_champ5id', 't2_champ5_sum1', 't2_champ5_sum2',
       't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills',
       't2_riftHeraldKills', 't2_ban1', 't2_ban2', 't2_ban3', 't2_ban4',
       't2_ban5'],
      dtype='object')

In [113]:
df.seasonId.value_counts()

seasonId
9    51490
Name: count, dtype: int64

In [114]:
df[['t1_champ1id','t1_champ2id']]

       t1_champ1id  t1_champ2id
0                8          432
1              119           39
2               18          141
3               57           63
4               19           29
...            ...          ...
51485           19          429
51486           90           32
51487          141           18
51488          121          236
51489           89            1

[51490 rows x 2 columns]

In [115]:
champ_data = json.load(open('champion_info.json'))
champ_data

{'type': 'champion',
 'version': '7.17.2',
 'data': {'1': {'title': 'the Dark Child',
   'id': 1,
   'key': 'Annie',
   'name': 'Annie'},
  '2': {'title': 'the Berserker', 'id': 2, 'key': 'Olaf', 'name': 'Olaf'},
  '3': {'title': 'the Colossus', 'id': 3, 'key': 'Galio', 'name': 'Galio'},
  '4': {'title': 'the Card Master',
   'id': 4,
   'key': 'TwistedFate',
   'name': 'Twisted Fate'},
  '5': {'title': 'the Seneschal of Demacia',
   'id': 5,
   'key': 'XinZhao',
   'name': 'Xin Zhao'},
  '6': {'title': 'the Dreadnought', 'id': 6, 'key': 'Urgot', 'name': 'Urgot'},
  '7': {'title': 'the Deceiver', 'id': 7, 'key': 'Leblanc', 'name': 'LeBlanc'},
  '8': {'title': 'the Crimson Reaper',
   'id': 8,
   'key': 'Vladimir',
   'name': 'Vladimir'},
  '9': {'title': 'the Harbinger of Doom',
   'id': 9,
   'key': 'Fiddlesticks',
   'name': 'Fiddlesticks'},
  '10': {'title': 'The Judicator', 'id': 10, 'key': 'Kayle', 'name': 'Kayle'},
  '11': {'title': 'the Wuju Bladesman',
   'id': 11,
   'key': 'MasterYi',
   'name': 'Master Yi'},
  '12': {'title': 'the Minotaur',
   'id': 12,
   'key': 'Alistar',
   'name': 'Alistar'},
  '13': {'title': 'the Rune Mage', 'id': 13, 'key': 'Ryze', 'name': 'Ryze'},
  '14': {'title': 'The Undead Juggernaut',
   'id': 14,
   'key': 'Sion',
   'name': 'Sion'},
  '15': {'title': 'the Battle Mistress',
   'id': 15,
   'key': 'Sivir',
   'name': 'Sivir'},
  '16': {'title': 'the Starchild',
   'id': 16,
   'key': 'Soraka',
   'name': 'Soraka'},
  '17': {'title': 'the Swift Scout',
   'id': 17,
   'key': 'Teemo',
   'name': 'Teemo'},
  '18': {'title': 'the Yordle Gunner',
   'id': 18,
   'key': 'Tristana',
   'name': 'Tristana'},
  '19': {'title': 'the Uncaged Wrath of Zaun',
   'id': 19,
   'key': 'Warwick',
   'name': 'Warwick'},
  '20': {'title': 'the Yeti Rider', 'id': 20, 'key': 'Nunu', 'name': 'Nunu'},
  '21': {'title': 'the Bounty Hunter',
   'id': 21,
   'key': 'MissFortune',
   'name': 'Miss Fortune'},
  '22': {'title': 'the Frost Archer', 'id': 22, 'key': 'Ashe', 'name': 'Ashe'},
  '23': {'title': 'the Barbarian King',
   'id': 23,
   'key': 'Tryndamere',
   'name': 'Tryndamere'},
  '24': {'title': 'Grandmaster at Arms',
   'id': 24,
   'key': 'Jax',
   'name': 'Jax'},
  '25': {'title': 'Fallen Angel',
   'id': 25,
   'key': 'Morgana',
   'name': 'Morgana'},
  '26': {'title': 'the Chronokeeper',
   'id': 26,
   'key': 'Zilean',
   'name': 'Zilean'},
  '27': {'title': 'the Mad Chemist',
   'id': 27,
   'key': 'Singed',
   'name': 'Singed'},
  '28': {'title': 'the Widowmaker',
   'id': 28,
   'key': 'Evelynn',
   'name': 'Evelynn'},
  '29': {'title': 'the Plague Rat',
   'id': 29,
   'key': 'Twitch',
   'name': 'Twitch'},
  '30': {'title': 'the Deathsinger',
   'id': 30,
   'key': 'Karthus',
   'name': 'Karthus'},
  '31': {'title': 'the Terror of the Void',
   'id': 31,
   'key': 'Chogath',
   'name': "Cho'Gath"},
  '32': {'title': 'the Sad Mummy', 'id': 32, 'key': 'Amumu', 'name': 'Amumu'},
  '33': {'title': 'the Armordillo',
   'id': 33,
   'key': 'Rammus',
   'name': 'Rammus'},
  '34': {'title': 'the Cryophoenix',
   'id': 34,
   'key': 'Anivia',
   'name': 'Anivia'},
  '35': {'title': 'the Demon Jester',
   'id': 35,
   'key': 'Shaco',
   'name': 'Shaco'},
  '36': {'title': 'the Madman of Zaun',
   'id': 36,
   'key': 'DrMundo',
   'name': 'Dr. Mundo'},
  '37': {'title': 'Maven of the Strings',
   'id': 37,
   'key': 'Sona',
   'name': 'Sona'},
  '38': {'title': 'the Void Walker',
   'id': 38,
   'key': 'Kassadin',
   'name': 'Kassadin'},
  '39': {'title': 'the Will of the Blades',
   'id': 39,
   'key': 'Irelia',
   'name': 'Irelia'},
  '40': {'title': "the Storm's Fury",
   'id': 40,
   'key': 'Janna',
   'name': 'Janna'},
  '41': {'title': 'the Saltwater Scourge',
   'id': 41,
   'key': 'Gangplank',
   'name': 'Gangplank'},
  '42': {'title': 'the Daring Bombardier',
   'id': 42,
   'key': 'Corki',
   'name': 'Corki'},
  '43': {'title': 'the Enlightened One',
   'id': 43,
   'key': 'Karma',
   'name': 'Karma'},
  '44': {'title': 'the Shield of Valoran',
   'id': 44,
   'key': 'Taric',
   'name': 'Taric'},
  '45': {'title': 'the Tiny Master of Evil',
   'id': 45,
   'key': 'Veigar',
   'name': 'Veigar'},
  '48': {'title': 'the Troll King',
   'id': 48,
   'key': 'Trundle',
   'name': 'Trundle'},
  '50': {'title': 'the Master Tactician',
   'id': 50,
   'key': 'Swain',
   'name': 'Swain'},
  '51': {'title': 'the Sheriff of Piltover',
   'id': 51,
   'key': 'Caitlyn',
   'name': 'Caitlyn'},
  '53': {'title': 'the Great Steam Golem',
   'id': 53,
   'key': 'Blitzcrank',
   'name': 'Blitzcrank'},
  '54': {'title': 'Shard of the Monolith',
   'id': 54,
   'key': 'Malphite',
   'name': 'Malphite'},
  '55': {'title': 'the Sinister Blade',
   'id': 55,
   'key': 'Katarina',
   'name': 'Katarina'},
  '56': {'title': 'the Eternal Nightmare',
   'id': 56,
   'key': 'Nocturne',
   'name': 'Nocturne'},
  '57': {'title': 'the Twisted Treant',
   'id': 57,
   'key': 'Maokai',
   'name': 'Maokai'},
  '58': {'title': 'the Butcher of the Sands',
   'id': 58,
   'key': 'Renekton',
   'name': 'Renekton'},
  '59': {'title': 'the Exemplar of Demacia',
   'id': 59,
   'key': 'JarvanIV',
   'name': 'Jarvan IV'},
  '60': {'title': 'the Spider Queen',
   'id': 60,
   'key': 'Elise',
   'name': 'Elise'},
  '61': {'title': 'the Lady of Clockwork',
   'id': 61,
   'key': 'Orianna',
   'name': 'Orianna'},
  '62': {'title': 'the Monkey King',
   'id': 62,
   'key': 'MonkeyKing',
   'name': 'Wukong'},
  '63': {'title': 'the Burning Vengeance',
   'id': 63,
   'key': 'Brand',
   'name': 'Brand'},
  '64': {'title': 'the Blind Monk',
   'id': 64,
   'key': 'LeeSin',
   'name': 'Lee Sin'},
  '67': {'title': 'the Night Hunter',
   'id': 67,
   'key': 'Vayne',
   'name': 'Vayne'},
  '68': {'title': 'the Mechanized Menace',
   'id': 68,
   'key': 'Rumble',
   'name': 'Rumble'},
  '69': {'title': "the Serpent's Embrace",
   'id': 69,
   'key': 'Cassiopeia',
   'name': 'Cassiopeia'},
  '72': {'title': 'the Crystal Vanguard',
   'id': 72,
   'key': 'Skarner',
   'name': 'Skarner'},
  '74': {'title': 'the Revered Inventor',
   'id': 74,
   'key': 'Heimerdinger',
   'name': 'Heimerdinger'},
  '75': {'title': 'the Curator of the Sands',
   'id': 75,
   'key': 'Nasus',
   'name': 'Nasus'},
  '76': {'title': 'the Bestial Huntress',
   'id': 76,
   'key': 'Nidalee',
   'name': 'Nidalee'},
  '77': {'title': 'the Spirit Walker',
   'id': 77,
   'key': 'Udyr',
   'name': 'Udyr'},
  '78': {'title': 'Keeper of the Hammer',
   'id': 78,
   'key': 'Poppy',
   'name': 'Poppy'},
  '79': {'title': 'the Rabble Rouser',
   'id': 79,
   'key': 'Gragas',
   'name': 'Gragas'},
  '80': {'title': 'the Artisan of War',
   'id': 80,
   'key': 'Pantheon',
   'name': 'Pantheon'},
  '81': {'title': 'the Prodigal Explorer',
   'id': 81,
   'key': 'Ezreal',
   'name': 'Ezreal'},
  '82': {'title': 'the Iron Revenant',
   'id': 82,
   'key': 'Mordekaiser',
   'name': 'Mordekaiser'},
  '83': {'title': 'Shepherd of Souls',
   'id': 83,
   'key': 'Yorick',
   'name': 'Yorick'},
  '84': {'title': 'the Fist of Shadow',
   'id': 84,
   'key': 'Akali',
   'name': 'Akali'},
  '85': {'title': 'the Heart of the Tempest',
   'id': 85,
   'key': 'Kennen',
   'name': 'Kennen'},
  '86': {'title': 'The Might of Demacia',
   'id': 86,
   'key': 'Garen',
   'name': 'Garen'},
  '89': {'title': 'the Radiant Dawn',
   'id': 89,
   'key': 'Leona',
   'name': 'Leona'},
  '90': {'title': 'the Prophet of the Void',
   'id': 90,
   'key': 'Malzahar',
   'name': 'Malzahar'},
  '91': {'title': "the Blade's Shadow",
   'id': 91,
   'key': 'Talon',
   'name': 'Talon'},
  '92': {'title': 'the Exile', 'id': 92, 'key': 'Riven', 'name': 'Riven'},
  '96': {'title': 'the Mouth of the Abyss',
   'id': 96,
   'key': 'KogMaw',
   'name': "Kog'Maw"},
  '98': {'title': 'the Eye of Twilight',
   'id': 98,
   'key': 'Shen',
   'name': 'Shen'},
  '99': {'title': 'the Lady of Luminosity',
   'id': 99,
   'key': 'Lux',
   'name': 'Lux'},
  '101': {'title': 'the Magus Ascendant',
   'id': 101,
   'key': 'Xerath',
   'name': 'Xerath'},
  '102': {'title': 'the Half-Dragon',
   'id': 102,
   'key': 'Shyvana',
   'name': 'Shyvana'},
  '103': {'title': 'the Nine-Tailed Fox',
   'id': 103,
   'key': 'Ahri',
   'name': 'Ahri'},
  '104': {'title': 'the Outlaw', 'id': 104, 'key': 'Graves', 'name': 'Graves'},
  '105': {'title': 'the Tidal Trickster',
   'id': 105,
   'key': 'Fizz',
   'name': 'Fizz'},
  '106': {'title': "the Thunder's Roar",
   'id': 106,
   'key': 'Volibear',
   'name': 'Volibear'},
  '107': {'title': 'the Pridestalker',
   'id': 107,
   'key': 'Rengar',
   'name': 'Rengar'},
  '110': {'title': 'the Arrow of Retribution',
   'id': 110,
   'key': 'Varus',
   'name': 'Varus'},
  '111': {'title': 'the Titan of the Depths',
   'id': 111,
   'key': 'Nautilus',
   'name': 'Nautilus'},
  '112': {'title': 'the Machine Herald',
   'id': 112,
   'key': 'Viktor',
   'name': 'Viktor'},
  '113': {'title': 'Fury of the North',
   'id': 113,
   'key': 'Sejuani',
   'name': 'Sejuani'},
  '114': {'title': 'the Grand Duelist',
   'id': 114,
   'key': 'Fiora',
   'name': 'Fiora'},
  '115': {'title': 'the Hexplosives Expert',
   'id': 115,
   'key': 'Ziggs',
   'name': 'Ziggs'},
  '117': {'title': 'the Fae Sorceress',
   'id': 117,
   'key': 'Lulu',
   'name': 'Lulu'},
  '119': {'title': 'the Glorious Executioner',
   'id': 119,
   'key': 'Draven',
   'name': 'Draven'},
  '120': {'title': 'the Shadow of War',
   'id': 120,
   'key': 'Hecarim',
   'name': 'Hecarim'},
  '121': {'title': 'the Voidreaver',
   'id': 121,
   'key': 'Khazix',
   'name': "Kha'Zix"},
  '122': {'title': 'the Hand of Noxus',
   'id': 122,
   'key': 'Darius',
   'name': 'Darius'},
  '126': {'title': 'the Defender of Tomorrow',
   'id': 126,
   'key': 'Jayce',
   'name': 'Jayce'},
  '127': {'title': 'the Ice Witch',
   'id': 127,
   'key': 'Lissandra',
   'name': 'Lissandra'},
  '131': {'title': 'Scorn of the Moon',
   'id': 131,
   'key': 'Diana',
   'name': 'Diana'},
  '133': {'title': "Demacia's Wings",
   'id': 133,
   'key': 'Quinn',
   'name': 'Quinn'},
  '134': {'title': 'the Dark Sovereign',
   'id': 134,
   'key': 'Syndra',
   'name': 'Syndra'},
  '136': {'title': 'The Star Forger',
   'id': 136,
   'key': 'AurelionSol',
   'name': 'Aurelion Sol'},
  '141': {'title': 'the Shadow Reaper',
   'id': 141,
   'key': 'Kayn',
   'name': 'Kayn'},
  '143': {'title': 'Rise of the Thorns',
   'id': 143,
   'key': 'Zyra',
   'name': 'Zyra'},
  '150': {'title': 'the Missing Link',
   'id': 150,
   'key': 'Gnar',
   'name': 'Gnar'},
  '154': {'title': 'the Secret Weapon',
   'id': 154,
   'key': 'Zac',
   'name': 'Zac'},
  '157': {'title': 'the Unforgiven',
   'id': 157,
   'key': 'Yasuo',
   'name': 'Yasuo'},
  '161': {'title': 'the Eye of the Void',
   'id': 161,
   'key': 'Velkoz',
   'name': "Vel'Koz"},
  '163': {'title': 'the Stoneweaver',
   'id': 163,
   'key': 'Taliyah',
   'name': 'Taliyah'},
  '164': {'title': 'the Steel Shadow',
   'id': 164,
   'key': 'Camille',
   'name': 'Camille'},
  '201': {'title': 'the Heart of the Freljord',
   'id': 201,
   'key': 'Braum',
   'name': 'Braum'},
  '202': {'title': 'the Virtuoso', 'id': 202, 'key': 'Jhin', 'name': 'Jhin'},
  '203': {'title': 'The Eternal Hunters',
   'id': 203,
   'key': 'Kindred',
   'name': 'Kindred'},
  '222': {'title': 'the Loose Cannon',
   'id': 222,
   'key': 'Jinx',
   'name': 'Jinx'},
  '223': {'title': 'the River King',
   'id': 223,
   'key': 'TahmKench',
   'name': 'Tahm Kench'},
  '236': {'title': 'the Purifier',
   'id': 236,
   'key': 'Lucian',
   'name': 'Lucian'},
  '238': {'title': 'the Master of Shadows',
   'id': 238,
   'key': 'Zed',
   'name': 'Zed'},
  '240': {'title': 'the Cantankerous Cavalier',
   'id': 240,
   'key': 'Kled',
   'name': 'Kled'},
  '245': {'title': 'the Boy Who Shattered Time',
   'id': 245,
   'key': 'Ekko',
   'name': 'Ekko'},
  '254': {'title': 'the Piltover Enforcer',
   'id': 254,
   'key': 'Vi',
   'name': 'Vi'},
  '266': {'title': 'the Darkin Blade',
   'id': 266,
   'key': 'Aatrox',
   'name': 'Aatrox'},
  '267': {'title': 'the Tidecaller', 'id': 267, 'key': 'Nami', 'name': 'Nami'},
  '268': {'title': 'the Emperor of the Sands',
   'id': 268,
   'key': 'Azir',
   'name': 'Azir'},
  '412': {'title': 'the Chain Warden',
   'id': 412,
   'key': 'Thresh',
   'name': 'Thresh'},
  '420': {'title': 'the Kraken Priestess',
   'id': 420,
   'key': 'Illaoi',
   'name': 'Illaoi'},
  '421': {'title': 'the Void Burrower',
   'id': 421,
   'key': 'RekSai',
   'name': "Rek'Sai"},
  '427': {'title': 'the Green Father',
   'id': 427,
   'key': 'Ivern',
   'name': 'Ivern'},
  '429': {'title': 'the Spear of Vengeance',
   'id': 429,
   'key': 'Kalista',
   'name': 'Kalista'},
  '432': {'title': 'the Wandering Caretaker',
   'id': 432,
   'key': 'Bard',
   'name': 'Bard'},
  '497': {'title': 'The Charmer', 'id': 497, 'key': 'Rakan', 'name': 'Rakan'},
  '498': {'title': 'the Rebel', 'id': 498, 'key': 'Xayah', 'name': 'Xayah'},
  '516': {'title': 'The Fire below the Mountain',
   'id': 516,
   'key': 'Ornn',
   'name': 'Ornn'}}}

In [116]:
df['t1_champ1']=df['t1_champ1id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t1_champ2']=df['t1_champ2id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t1_champ3']=df['t1_champ3id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t1_champ4']=df['t1_champ4id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t1_champ5']=df['t1_champ5id'].apply(lambda x: champ_data['data'][str(x)]['name'])

df['t2_champ1']=df['t2_champ1id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t2_champ2']=df['t2_champ2id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t2_champ3']=df['t2_champ3id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t2_champ4']=df['t2_champ4id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t2_champ5']=df['t2_champ5id'].apply(lambda x: champ_data['data'][str(x)]['name'])

In [117]:
df

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t1_champ1,t1_champ2,t1_champ3,t1_champ4,t1_champ5,t2_champ1,t2_champ2,t2_champ3,t2_champ4,t2_champ5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,Vladimir,Bard,Kog'Maw,Master Yi,Viktor,Graves,Xayah,Darius,Zed,Thresh
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,Draven,Irelia,Nidalee,Kayle,Shaco,Malphite,Morgana,Hecarim,Yasuo,Riven
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,Tristana,Kayn,Nami,Rumble,Kassadin,Cassiopeia,Thresh,Jayce,Jax,Ashe
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,Maokai,Brand,Twitch,Orianna,Dr. Mundo,Malzahar,Warwick,Thresh,Riven,Ashe
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,Warwick,Twitch,Janna,Draven,Syndra,Sona,Jarvan IV,Kayn,Kassadin,Caitlyn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,3308904636,1503076540231,1944,9,2,1,2,2,0,2,...,Warwick,Kalista,Talon,Bard,Lee Sin,Veigar,Yorick,Vayne,Janna,Gragas
51486,3215685759,1496957179355,3304,9,2,1,1,2,2,2,...,Malzahar,Amumu,Cho'Gath,Thresh,Tristana,Shyvana,Kalista,Leona,Nasus,Veigar
51487,3322765040,1504029863961,2156,9,2,2,2,2,0,1,...,Kayn,Tristana,Bard,Ezreal,Rumble,Annie,Draven,Rammus,Karma,Lux
51488,3256675373,1499562036246,1475,9,2,2,2,2,0,2,...,Kha'Zix,Lucian,Illaoi,Braum,Lux,Miss Fortune,Nocturne,Morgana,Karthus,Master Yi
51489,3317333020,1503612754059,1445,9,1,1,1,1,1,2,...,Leona,Annie,Camille,Sejuani,Jhin,Brand,Teemo,Twitch,Kha'Zix,Renekton

In [118]:

df = df[['t1_champ1', 't1_champ2','t1_champ3','t1_champ4','t1_champ5', 't2_champ1','t2_champ2','t1_champ3','t2_champ4','t2_champ5','firstBlood','firstDragon','firstTower','firstBaron','winner']]

In [119]:
df

,t1_champ1,t1_champ2,t1_champ3,t1_champ4,t1_champ5,t2_champ1,t2_champ2,t1_champ3,t2_champ4,t2_champ5,firstBlood,firstDragon,firstTower,firstBaron,winner
0,Vladimir,Bard,Kog'Maw,Master Yi,Viktor,Graves,Xayah,Kog'Maw,Zed,Thresh,2,1,1,1,1
1,Draven,Irelia,Nidalee,Kayle,Shaco,Malphite,Morgana,Nidalee,Yasuo,Riven,1,1,1,0,1
2,Tristana,Kayn,Nami,Rumble,Kassadin,Cassiopeia,Thresh,Nami,Jax,Ashe,2,2,1,1,1
3,Maokai,Brand,Twitch,Orianna,Dr. Mundo,Malzahar,Warwick,Twitch,Riven,Ashe,1,1,1,1,1
4,Warwick,Twitch,Janna,Draven,Syndra,Sona,Jarvan IV,Janna,Kassadin,Caitlyn,2,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,Warwick,Kalista,Talon,Bard,Lee Sin,Veigar,Yorick,Talon,Janna,Gragas,1,2,2,0,2
51486,Malzahar,Amumu,Cho'Gath,Thresh,Tristana,Shyvana,Kalista,Cho'Gath,Nasus,Veigar,1,2,1,2,2
51487,Kayn,Tristana,Bard,Ezreal,Rumble,Annie,Draven,Bard,Karma,Lux,2,1,2,0,2
51488,Kha'Zix,Lucian,Illaoi,Braum,Lux,Miss Fortune,Nocturne,Illaoi,Karthus,Master Yi,2,2,2,0,2
51489,Leona,Annie,Camille,Sejuani,Jhin,Brand,Teemo,Camille,Kha'Zix,Renekton,1,2,1,1,1

In [120]:
encodings = [pd.get_dummies(df['t1_champ1'], prefix='t1') for col in ['t1_champ1', 't1_champ2','t1_champ3','t1_champ4','t1_champ5']]
combined_df1 = sum(encodings)
encodings2 =[pd.get_dummies(df['t2_champ1'], prefix='t2') for col in ['t2_champ1', 't2_champ2','t2_champ3','t2_champ4','t2_champ5']]
combined_df2 = sum(encodings2)

In [121]:
df = df.join(combined_df1).join(combined_df2)

In [122]:
df

,t1_champ1,t1_champ2,t1_champ3,t1_champ4,t1_champ5,t2_champ1,t2_champ2,t1_champ3,t2_champ4,t2_champ5,...,t2_Xayah,t2_Xerath,t2_Xin Zhao,t2_Yasuo,t2_Yorick,t2_Zac,t2_Zed,t2_Ziggs,t2_Zilean,t2_Zyra
0,Vladimir,Bard,Kog'Maw,Master Yi,Viktor,Graves,Xayah,Kog'Maw,Zed,Thresh,...,0,0,0,0,0,0,0,0,0,0
1,Draven,Irelia,Nidalee,Kayle,Shaco,Malphite,Morgana,Nidalee,Yasuo,Riven,...,0,0,0,0,0,0,0,0,0,0
2,Tristana,Kayn,Nami,Rumble,Kassadin,Cassiopeia,Thresh,Nami,Jax,Ashe,...,0,0,0,0,0,0,0,0,0,0
3,Maokai,Brand,Twitch,Orianna,Dr. Mundo,Malzahar,Warwick,Twitch,Riven,Ashe,...,0,0,0,0,0,0,0,0,0,0
4,Warwick,Twitch,Janna,Draven,Syndra,Sona,Jarvan IV,Janna,Kassadin,Caitlyn,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,Warwick,Kalista,Talon,Bard,Lee Sin,Veigar,Yorick,Talon,Janna,Gragas,...,0,0,0,0,0,0,0,0,0,0
51486,Malzahar,Amumu,Cho'Gath,Thresh,Tristana,Shyvana,Kalista,Cho'Gath,Nasus,Veigar,...,0,0,0,0,0,0,0,0,0,0
51487,Kayn,Tristana,Bard,Ezreal,Rumble,Annie,Draven,Bard,Karma,Lux,...,0,0,0,0,0,0,0,0,0,0
51488,Kha'Zix,Lucian,Illaoi,Braum,Lux,Miss Fortune,Nocturne,Illaoi,Karthus,Master Yi,...,0,0,0,0,0,0,0,0,0,0
51489,Leona,Annie,Camille,Sejuani,Jhin,Brand,Teemo,Camille,Kha'Zix,Renekton,...,0,0,0,0,0,0,0,0,0,0

In [123]:
df = df.drop(['t1_champ1', 't1_champ2','t1_champ3','t1_champ4','t1_champ5', 't2_champ1','t2_champ2','t1_champ3','t2_champ4','t2_champ5'], axis=1)

In [124]:
df

,firstBlood,firstDragon,firstTower,firstBaron,winner,t1_Aatrox,t1_Ahri,t1_Akali,t1_Alistar,t1_Amumu,...,t2_Xayah,t2_Xerath,t2_Xin Zhao,t2_Yasuo,t2_Yorick,t2_Zac,t2_Zed,t2_Ziggs,t2_Zilean,t2_Zyra
0,2,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,2,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,1,2,2,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51486,1,2,1,2,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51487,2,1,2,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51488,2,2,2,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51489,1,2,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [125]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [126]:
X , y = df.drop('winner',axis=1), df['winner']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [127]:
clf = RandomForestClassifier(n_jobs=-1)
clf.fit(X_train,y_train)

RandomForestClassifier(n_jobs=-1)

In [128]:
clf.score(X_test,y_test)

0.7910273839580501

In [129]:
importances = dict(zip(X.columns,clf.feature_importances_))
sorted_importances = sorted(importances.items(), key=lambda x: x[1], reverse=True)
sorted_importances

[('firstBaron', 0.2148604637263698),
 ('firstTower', 0.1309584389936164),
 ('firstDragon', 0.07725752958407855),
 ('firstBlood', 0.0248522992537728),
 ('t1_Thresh', 0.005307404004935666),
 ('t1_Tristana', 0.005299587340044474),
 ('t2_Thresh', 0.005117282823912987),
 ('t2_Tristana', 0.005098010105082076),
 ('t2_Kayn', 0.004566014277438264),
 ('t1_Vayne', 0.00454826531715236),
 ('t1_Kayn', 0.00449827155160723),
 ('t2_Vayne', 0.00425461979088308),
 ('t1_Yasuo', 0.0041482735067470775),
 ('t1_Twitch', 0.004007713655071508),
 ('t2_Jhin', 0.0038531931889509165),
 ('t1_Lee Sin', 0.003830422013449991),
 ('t2_Lux', 0.0037976546043270065),
 ('t1_Jinx', 0.0037448377798788967),
 ('t1_Lux', 0.0037200489047493385),
 ('t2_Jinx', 0.0037158201169564787),
 ('t1_Janna', 0.0036611594704161103),
 ('t1_Lucian', 0.003653302615924313),
 ('t2_Yasuo', 0.003623604014431812),
 ('t1_Zed', 0.0035981023094617207),
 ('t2_Twitch', 0.0035910496835171507),
 ('t2_Xayah', 0.0035831652570096195),
 ('t1_Jhin', 0.003534201377504964),
 ('t2_Lucian', 0.003514236816146653),
 ('t1_Jax', 0.0034902332693034425),
 ('t2_Lee Sin', 0.0034878063039068554),
 ('t2_Orianna', 0.0034332378990931662),
 ('t2_Janna', 0.0034233687985082083),
 ('t1_Master Yi', 0.003318640414857866),
 ('t1_Ahri', 0.003306882420227061),
 ('t2_Zed', 0.0032944108191754655),
 ('t2_Gragas', 0.0032721212142936378),
 ('t2_Lulu', 0.003266168932575969),
 ('t1_Caitlyn', 0.0032191170363487097),
 ('t1_Warwick', 0.003184963928185155),
 ('t2_Rakan', 0.003175140739489335),
 ('t2_Jax', 0.003169846728265069),
 ('t1_Orianna', 0.0031471967118328285),
 ('t2_Blitzcrank', 0.003118255379917499),
 ('t2_Warwick', 0.0031119860375521946),
 ('t1_Blitzcrank', 0.0030670129993401944),
 ('t2_Caitlyn', 0.0030612995997640925),
 ('t1_Ekko', 0.0030458557804400087),
 ('t1_Xayah', 0.0030160315850419474),
 ('t1_Miss Fortune', 0.0030111738623008577),
 ('t2_Soraka', 0.0030059029600569363),
 ('t2_Ahri', 0.002996750544644677),
 ('t2_Morgana', 0.002994152912297049),
 ('t1_Gragas', 0.002951088055993692),
 ('t2_Riven', 0.002921408995324962),
 ('t1_Rakan', 0.0029169730493973423),
 ('t1_Soraka', 0.002877405372122655),
 ('t2_Miss Fortune', 0.002861050952137364),
 ('t1_Ezreal', 0.0028561256324213936),
 ('t1_Lulu', 0.0028165648063508252),
 ('t1_Riven', 0.002810037562927647),
 ('t2_Ekko', 0.002750537194812044),
 ('t1_Jarvan IV', 0.002738378167258575),
 ('t1_Ashe', 0.002735317480409648),
 ('t2_Jarvan IV', 0.0027060116359069767),
 ('t1_Morgana', 0.0026925100760319324),
 ('t1_Leona', 0.002674053627649745),
 ("t1_Kha'Zix", 0.002670155684058573),
 ('t2_Master Yi', 0.002643862919519075),
 ('t2_Sona', 0.0025698014204505477),
 ('t1_Draven', 0.0025563254629571365),
 ('t2_Ornn', 0.002545040554035144),
 ('t1_Gangplank', 0.0025235264381691614),
 ('t1_Garen', 0.0025173197443862307),
 ('t2_Teemo', 0.002506611936802037),
 ('t2_Gangplank', 0.002492920223934164),
 ('t2_Nasus', 0.002481844392359708),
 ('t2_Draven', 0.002469303925564996),
 ('t2_Ashe', 0.0024461724164794264),
 ('t1_Renekton', 0.0024367972007940802),
 ('t2_Malzahar', 0.0024329555339450176),
 ('t2_Brand', 0.0024326228861068343),
 ('t2_Leona', 0.002414557202287773),
 ('t1_Gnar', 0.002411055192920673),
 ("t2_Cho'Gath", 0.002389189995966724),
 ('t1_Veigar', 0.002375848882402867),
 ('t2_Renekton', 0.0023751505770698927),
 ('t1_Darius', 0.0023457723119662877),
 ('t2_Bard', 0.0023424099523053406),
 ('t2_Darius', 0.0023352208955143817),
 ('t1_Maokai', 0.0023334173215427165),
 ('t1_Sona', 0.0023293363592541954),
 ('t1_Brand', 0.0023277993464071393),
 ('t1_Nami', 0.0023021970731195687),
 ('t2_Nami', 0.002296282034539248),
 ('t1_Sivir', 0.0022944553036788663),
 ('t1_Bard', 0.0022930466849943073),
 ('t1_Xin Zhao', 0.002279339069522451),
 ('t1_Nasus', 0.002269022755657826),
 ("t1_Cho'Gath", 0.0022605948093665108),
 ('t1_Tryndamere', 0.002260204998692671),
 ('t1_Teemo', 0.0022228525304935558),
 ('t2_Sivir', 0.0022177476965772537),
 ('t1_Fizz', 0.002209116877462795),
 ('t1_Malzahar', 0.0022030078480736563),
 ('t2_Ezreal', 0.0022019329139439004),
 ('t2_Kalista', 0.002198895211493365),
 ('t2_Garen', 0.0021887723652353995),
 ('t1_Syndra', 0.002184101926792754),
 ('t1_Sejuani', 0.0021720145566637918),
 ('t1_Karma', 0.0021420210294648043),
 ("t1_Vel'Koz", 0.002138382873626112),
 ('t1_Talon', 0.002137137058885967),
 ('t2_Maokai', 0.0021153612449737254),
 ('t1_Katarina', 0.0021076647403298907),
 ("t2_Kha'Zix", 0.0021004395754933873),
 ('t1_Ornn', 0.0020980113903910523),
 ('t2_Fizz', 0.0020715556791574778),
 ('t2_Veigar', 0.0020669030180092353),
 ('t2_Tryndamere', 0.0020449392792419503),
 ('t2_Vladimir', 0.0020259299883589586),
 ('t1_Braum', 0.0020138412131120984),
 ('t2_Jayce', 0.0020108635205119928),
 ('t1_Kassadin', 0.002003367519286754),
 ('t2_Shen', 0.001990538853687153),
 ('t2_Talon', 0.001976850394478301),
 ('t2_Akali', 0.0019706765011899786),
 ('t2_Alistar', 0.001962274501747274),
 ('t2_Braum', 0.001942675941011718),
 ('t1_Twisted Fate', 0.0019252815277987052),
 ('t1_Akali', 0.0019236199587843443),
 ('t2_Twisted Fate', 0.0019208368516192733),
 ('t1_Alistar', 0.0019021756932339547),
 ('t2_Varus', 0.0018939464437189005),
 ('t1_Diana', 0.0018937523829366503),
 ('t2_Xin Zhao', 0.0018697315561817611),
 ('t2_Syndra', 0.0018553316425320683),
 ('t1_Shen', 0.0018507892891469666),
 ('t1_Kalista', 0.0018423307546190308),
 ('t1_Elise', 0.0018265010103044143),
 ('t2_Gnar', 0.0018191670871484191),
 ("t1_Kog'Maw", 0.001812053425486949),
 ('t1_Vladimir', 0.001795179542178815),
 ('t1_Cassiopeia', 0.0017827068623560032),
 ('t2_Katarina', 0.0017790797652545221),
 ('t2_Kassadin', 0.0017786287740102172),
 ('t1_Ziggs', 0.0017774404741069264),
 ('t1_Annie', 0.0017557672873054896),
 ('t2_Annie', 0.0017514008789566704),
 ("t2_Kog'Maw", 0.0017492760011651304),
 ('t2_Diana', 0.0017421853311032848),
 ('t1_Vi', 0.0017411779215858619),
 ('t2_Fiora', 0.0017392200175848002),
 ("t2_Vel'Koz", 0.0017299404937129732),
 ('t1_Jayce', 0.0017252260182068573),
 ('t1_Varus', 0.0017113712677696525),
 ('t2_Sejuani', 0.0017108758826544243),
 ('t1_Anivia', 0.001700669124162209),
 ('t2_Elise', 0.0016914475854961253),
 ('t2_Shaco', 0.0016833758401456837),
 ('t1_Galio', 0.0016809280231160747),
 ('t2_Cassiopeia', 0.0016617255474870721),
 ('t1_Rammus', 0.0016538497123690702),
 ('t2_Rammus', 0.0016484598079797217),
 ('t2_Malphite', 0.0016432129257784025),
 ('t2_Taric', 0.0016239688516337246),
 ('t1_Irelia', 0.0016066216213209159),
 ('t1_Fiora', 0.001599895497930458),
 ('t1_Zac', 0.001596899188338822),
 ('t2_Karma', 0.001589617190025869),
 ('t2_Zyra', 0.0015891675472059178),
 ('t1_Kennen', 0.0015693478272941087),
 ('t1_Corki', 0.0015533213834565864),
 ('t2_Galio', 0.0015327387816997228),
 ('t2_Amumu', 0.001514317994283339),
 ('t1_Shaco', 0.0014942429766490275),
 ('t2_Pantheon', 0.001483697144014237),
 ('t2_Vi', 0.0014786861457389447),
 ('t2_Corki', 0.0014706829437628216),
 ('t2_Shyvana', 0.0014644773620930032),
 ('t1_Pantheon', 0.0014518547892977032),
 ('t1_Taric', 0.0014394047556822568),
 ('t1_Malphite', 0.0014361229868333028),
 ('t1_Shyvana', 0.0014343810189378712),
 ('t1_Urgot', 0.0014267979262196737),
 ('t2_Taliyah', 0.0014250241449048032),
 ('t2_Urgot', 0.001421952390546015),
 ('t1_Trundle', 0.0014100210004624363),
 ('t2_LeBlanc', 0.0013961342482506646),
 ('t2_Irelia', 0.0013519841246687737),
 ('t2_Nautilus', 0.0013502859668090888),
 ('t2_Camille', 0.001349171090051432),
 ('t1_LeBlanc', 0.001348216094486424),
 ('t1_Amumu', 0.0013458058982228618),
 ('t2_Ziggs', 0.0013381731512450165),
 ('t1_Camille', 0.0013357493347101249),
 ('t2_Nidalee', 0.0013283390325783508),
 ('t1_Wukong', 0.0013236279887455812),
 ('t1_Kled', 0.001322706379873369),
 ('t2_Xerath', 0.001318958901014987),
 ('t2_Kayle', 0.0013188078916308093),
 ('t2_Tahm Kench', 0.0013064443534853858),
 ('t1_Taliyah', 0.0013052552992983307),
 ('t2_Kennen', 0.001290428550237563),
 ('t1_Sion', 0.001284624837047895),
 ('t2_Hecarim', 0.0012838396632868358),
 ('t2_Fiddlesticks', 0.00128110275801223),
 ('t2_Sion', 0.001277041741634576),
 ('t2_Anivia', 0.001265274579960437),
 ('t2_Zilean', 0.0012591044546575148),
 ('t2_Wukong', 0.0012558189182761486),
 ('t1_Fiddlesticks', 0.0012481801011095142),
 ('t1_Hecarim', 0.001246189335227912),
 ('t1_Yorick', 0.0012376383914321166),
 ('t1_Rengar', 0.001233504470859701),
 ('t1_Heimerdinger', 0.001229593098907598),
 ('t1_Zyra', 0.0012290748333346013),
 ('t1_Rumble', 0.001225511329940878),
 ('t1_Viktor', 0.00121660509373729),
 ('t2_Heimerdinger', 0.0012132936929943785),
 ('t1_Poppy', 0.0012124075906501052),
 ('t2_Trundle', 0.0012111469250115497),
 ('t1_Nautilus', 0.0012031160740886022),
 ('t1_Tahm Kench', 0.0011849637514662094),
 ('t2_Graves', 0.0011789417309411778),
 ('t2_Zac', 0.0011762028744769035),
 ('t1_Illaoi', 0.0011732249025108736),
 ('t2_Kled', 0.0011717379463153032),
 ('t1_Udyr', 0.0011405953050147271),
 ('t2_Viktor', 0.001126504470031493),
 ('t2_Dr. Mundo', 0.0011263946245330214),
 ('t2_Rumble', 0.001124341929167269),
 ('t2_Evelynn', 0.0011146579376200435),
 ('t1_Evelynn', 0.0011144718211446101),
 ('t2_Poppy', 0.001113056330221256),
 ('t2_Swain', 0.0011093323409599733),
 ('t1_Graves', 0.0011030370615400542),
 ('t1_Mordekaiser', 0.0010871415163069941),
 ('t2_Kindred', 0.0010832831115884863),
 ('t1_Nocturne', 0.0010776941075681334),
 ('t1_Dr. Mundo', 0.0010658538730701687),
 ('t2_Udyr', 0.0010327239271697394),
 ('t1_Quinn', 0.001019603044396998),
 ('t2_Ryze', 0.0010195975188352063),
 ('t2_Olaf', 0.0009969919839050375),
 ('t1_Azir', 0.0009967678103798264),
 ('t1_Swain', 0.000991406373215861),
 ('t2_Singed', 0.0009911439698708376),
 ('t2_Rengar', 0.0009869474911100382),
 ('t2_Illaoi', 0.000984169770871764),
 ('t1_Singed', 0.0009835597615037545),
 ('t1_Nidalee', 0.0009675819595144359),
 ('t1_Kayle', 0.000966522094273867),
 ("t2_Rek'Sai", 0.0009634169072343303),
 ('t1_Olaf', 0.0009619154976068554),
 ('t1_Xerath', 0.0009520881383592554),
 ("t1_Rek'Sai", 0.0009482095971789368),
 ('t1_Lissandra', 0.0009401871068054762),
 ('t2_Nocturne', 0.000931523781587245),
 ('t2_Aurelion Sol', 0.0009276758283091453),
 ('t2_Volibear', 0.0009257681001728306),
 ('t1_Ivern', 0.0008795603882585945),
 ('t1_Kindred', 0.0008295509017659169),
 ('t2_Quinn', 0.0008064634421024572),
 ('t2_Lissandra', 0.0008050448740885948),
 ('t1_Zilean', 0.0008014620011073625),
 ('t1_Volibear', 0.0007974689215804278),
 ('t1_Aatrox', 0.0007963939794991988),
 ('t2_Nunu', 0.0007939637925703561),
 ('t1_Ryze', 0.0007776412938740184),
 ('t1_Aurelion Sol', 0.0007673657571631523),
 ('t2_Mordekaiser', 0.0007531407550330888),
 ('t2_Karthus', 0.0007236917986058383),
 ('t2_Yorick', 0.0007036835358277184),
 ('t2_Ivern', 0.0006847170051107156),
 ('t1_Karthus', 0.0006190580246500715),
 ('t2_Azir', 0.0005803703958102626),
 ('t2_Aatrox', 0.0005660199370586343),
 ('t1_Nunu', 0.0005592229727576143),
 ('t1_Skarner', 0.00043209340117115845),
 ('t2_Skarner', 0.00024076082731281975)]